[26기 김여름] Homes-navigation bar 구현
wecode-bootcamp-korea/26-1st-Homes-frontend pull request #1
Opened 2021-11-02 14:13 UTC by sunmerrr

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 네비게이션 바 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 네비게이션 바 메뉴
- 전반적인 네비게이션 바 레이아이웃

2. 메뉴 드롭다운
- css 를 이용해서 메뉴 드롭다운 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- trasition 과 transfrom 을 이용해서 움직임을 부드럽게 조작할 수 있게되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-11-02 15:51 UTC, sunmerrr commented
해당 브랜치에 포함되면 안되는 파일이 포함된 채로 push 가 되어서 변경사항을 없애고 다시 푸시하느라 포스푸시를 하게 되었습니다. 앞으로는 처음부터 잘 확인하고 올리겠습니다.

2021-11-03 01:20 UTC, younuk23 commented on src/component/Nav/Categories/Categories.js
> +            alt="furnitureImg"
alt 는 대체텍스트의 역할을 하기 때문에 카멜케이스보다는 일반적인 영문법을 지켜서 작성하시는게 좋습니다!

2021-11-03 01:22 UTC, younuk23 commented on src/component/Nav/Categories/Categories.js
> +        <li className="category">
유니크한 className을 부여해서 다른 요소들에게 영향을 안미치게 하려면 최상위 태그에 클레스네임을 부여해주는 것이 좋습니다. 지금은 최상위 태그인 div 가 아니라 차상위인 li에 부여되어있네요!! 그리고 최상위 해당 목적으로 사용하는 최상위 태그의 className은 예외적으로 camelCase가 아니라 컴포넌트 이름과 동일하게 PascalCase로 지어주는게 혹여라도 className이 겹칠 염려가 없습니다! 이부분 적용해주시고 팀원분들이랑도 공유해주세요!

2021-11-03 01:44 UTC, younuk23 reviewed
고생하셨습니다 여름님 리뷰 확인 및 반영해주세요 👍

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Categories/Categories.scss
> +      }
컴포넌트에 없는 요소에 대한 스타일링이 scss 파일에 포함되어있네요.
컴포넌트는 독립적이고 재사용될 수 있어야 합니다.
어떤 컴포넌트에 대한 스타일시트에서 컴포넌트 외의 요소에 대해서 접근해서 스타일을 부여한다면 그 컴포넌트는 독립적이라고 볼 수 없습니다.
컴포넌트의 스타일 시트는 해당 컴포넌트에 대한 스타일만 진행해주세요!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Categories/Categories.scss
> +            width: 170px;
width가 padding 보다 위에 기입되는 게 css 작성순서 컨벤션상 적절하겠네요! 전반적으로 한번 점검해주세요!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Categories/Categories.scss
> +        ul.categories {
ul.categories 처럼 모든 className에 대해서 태그를 같이 병행해서 작성하실 필요는 없습니다! 필요한 상황에서만 적용해주시면 됩니다!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Categories/Categories.scss
> +              // transform: translateX(-20px) translateY(20px);
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Nav.js
> +              {/* 상수 데이터와 함께 컴포넌트로 따로 뺄 수 있도록 */}
```suggestion
              // TODO: 상수 데이터와 함께 컴포넌트로 따로 빼기
```
나중에 고쳐야 하는 경우나 더 해야 하는 경우는 주석에 TODO, TOFIX 등의 preset 을 붙이는 것이 알아보고 검색해서 찾아오기 더 쉽습니다!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Nav.js
> +              {/* 상수 데이터와 함께 컴포넌트로 따로 뺄 수 있도록 */}
적으신대로 반복되는 UI 는 map을 이용해서 표현할 수 있도록 해보세요!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Nav.scss
> +    flex-direction: row;
row 는 기본값입니다! 생략가능합니다

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Nav.js
> +      <header className="header">
최상위 className 신경써주세요!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Nav.scss
> +  width: 100%;
fixed면서 viewport 좌우로 꽉 차게 하고싶으신거면 left:0, right:0 으로도 표현가능합니다 참고하시면 됩니다!

2021-11-03 01:44 UTC, younuk23 commented on src/component/Nav/Nav.scss
> +      align-items: center;
자주 함께 사용되는 이런 속성들은 sass mixin 으로 만들어보셔도 좋을 것 같네요! mixin을 함수형태로 만들어서 justify-content, align-items 등 속성은 인자로 받을 수 있게 하면 더 좋고요!!

2021-11-03 01:46 UTC, younuk23 commented
해당 브랜치에 포함되면 안되는 파일이 포함된 채로 push 가 되어서 변경사항을 없애고 다시 푸시하느라 포스푸시를 하게 되었습니다. 앞으로는 처음부터 잘 확인하고 올리겠습니다.
=> 푸쉬 하고나서 확인하시는 습관이랑 Git 기능들 잘 사용해서 원하는대로 변경이력 잘 조정하시는 것 너무 좋네요 👍 

- PR 본문 잘 작성해주세요! 최근 작업주제 체크가 안되어있습니다.
- 구현사항 설명도 어떻게(how)에 집중해서 좀 더 자세히 작성하면 좋습니다! 지금은 크게 작성할 내용이 없어보이지만 앞으로 이 기능을 내가 어떻게 구현했는지를 잘 적으면 본인의 학습 정리에도 도움이 되고 나중에 내가 어떤 고민을 하고 성장했는지 스스로 회고하기 + 보여주기의 역할도 할 수 있으니까 고민해서 적어보세요!!

2021-11-03 02:32 UTC, sunmerrr commented on src/component/Nav/Categories/Categories.js
> +            alt="furnitureImg"
넵! 알맞게 작성하여 반영하도록 하겠습니다:)

2021-11-03 02:32 UTC, sunmerrr commented on src/component/Nav/Categories/Categories.js
> +        <li className="category">
넵 ! 팀원들에게 공유하였습니다. 주의해서 작성하겠습니다

2021-11-05 04:56 UTC, younuk23 requested changes
고생하셨습니다 여름님 리뷰 확인 및 반영해주세요!!

2021-11-05 04:56 UTC, younuk23 commented on src/component/Nav/CategoryTable/CategoryTable.js
> +            {this.state.showMenu
여름님! push 하시고 나시고 sider에서 리뷰달린 것 없는지 확인하고 리뷰 달린 것 있으시면 반영해주세요!!
구조분해할당 같은 경우에는 이상황에서는 한번만 쓰이는 변수인 것 같아서 구지 분해할당 할 필요는 없어보이는데 key prop 등 다른 리뷰들은 다 반영해주세요!

2021-11-05 04:56 UTC, younuk23 commented on src/component/Nav/CategoryTable/CategoryTable.js
> +              : null}
true 일 때만 렌더링이 되면 된다면 삼항연산자가 아니라 && 연산자를 이용하는것이 더 간결합니다!

2021-11-05 04:56 UTC, younuk23 commented on src/component/Nav/CategoryTable/CategoryTable.scss
> +    .categoryMenu {
style을 부여하지 않을 경우에는 className을 굳이 부여하고 적을 필요 없습니다!

2021-11-05 04:56 UTC, younuk23 commented on src/component/Nav/FurnitureTable/FurnitureTable.scss
> +      .categoryList {
이 컴포넌트에 없는 요소에 대한 스타일링이 scss 파일에 포함되어있네요.
컴포넌트는 독립적이고 재사용될 수 있어야 합니다.
어떤 컴포넌트에 대한 스타일시트에서 컴포넌트 외의 요소에 대해서 접근해서 스타일을 부여한다면 그 컴포넌트는 독립적이라고 볼 수 없습니다.
컴포넌트의 스타일 시트는 해당 컴포넌트에 대한 스타일만 진행해주세요!

2021-11-05 04:56 UTC, younuk23 commented on src/component/Nav/Nav.js
> +    fetch('http://localhost:3000/data/Categories.json')
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2021-11-05 04:56 UTC, younuk23 commented on src/component/Nav/component/Button.js
> +          {data.link && (
data.link는 데이터 구조를 봤을때 항상 존재하는 것 같은데 혹시 조건을 부여하신 이유가 있나요??

2021-11-05 04:56 UTC, younuk23 commented on src/styles/variable.scss
> +
기본값으로 0 말고 가장 많이 쓰이는 center등의 속성을 부여해두는게 좀 더 효율적일 것 같습니다!!

2021-11-05 06:09 UTC, younuk23 requested changes
여름님! localhost:3000 제거하는 것 및 key prop, destructuring 등 반영 안됬는데 resolve 누르신 것 몇개 있는 것 같네요!! 반영 다 하시고 나서 resolve 눌러주세요!!
***
그리고 sider 같은 경우에는 resolve 눌러주시면 되고 제 코멘트는 resolve누를는 것 보다 그냥 놔두시거나 답글로 수정 완료됬다고 달아주시면 제가 진짜 반영됬는지 확인하기 편할 것 같아요!!
반영하시고 나면 머지하겠습니다!

2021-11-05 06:09 UTC, younuk23 commented on src/component/Nav/Nav.js
> +    fetch('http://localhost:3000/data/Categories.json')
여름님 이부분 반영 안됬습니다!

2021-11-05 09:24 UTC, younuk23 approved these changes
LGTM 👍 
첫 머지 축하드립니다~~!!

2021-11-05 09:24 UTC, merged