Add: Store 페이지 Lay-out 작업 완료, 기능 구현 시작
wecode-bootcamp-korea/26-1st-Homes-frontend pull request #2
Opened 2021-11-02 15:17 UTC by betterplaywon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- filter메서드를 활용한 제품 나열 기능 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

1. Mock data를 활용한 Layout 작업
- HTML, CSS를 활용한 기본 Layout 구성 완료 
- data의 수에 따라 웹페이지에 들어오는 Component의 개수 조정

2. selector tag를 이용한 menu bar 제작
- filter 메서드를 활용해 menu를 클릭하면 조건에 따른 Component를 보여줄 수 있게 구현 계획.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- Component와 Mock data, map 메서드를 활용해 레이아웃 구성을 효율적으로 할 수 있었습니다.
- selector 라는 tag로 menu를 만들 수 있다는 점을 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-11-03 01:50 UTC, younuk23 commented
- PR 본문 확인해주세요! 최근 작업 주제 체크 안되어있습니다.
- 구현사항 설명 작성시 조금 더 어떻게(HOW)에 초점을 맞춰서 작성해주세요!!
구현사항을 잘 적으면서 내가 어떻게 구현했는지 스스로 이해도를 점검해볼 수 있으며 나중에 내가 어떤 고민을 하고 문제를 어떻게 해결했는지 점검해보면서 스스로를 회고해볼 수 있는 좋은 자산이 됩니다!
다른 누구도 아닌 자신을 위한 기록이니까 잘 기록해보세요!!
예시) data의 수에 따라 웹페이지에 들어오는 Component의 개수 조정
=> props로 받는 data를 map을 통해 Card Component로 변환하여서 data의 수만큼 카드 컴포넌트가 생성될 수 있도록 구현

2021-11-03 02:07 UTC, younuk23 requested changes
수고하셨습니다 지원님 리뷰 확인 및 반영해주세요!

2021-11-03 02:07 UTC, yeonuk-hwang commented on src/component/ProductContainer/ProductContainer.js
> +          <div className="brandName">{this.props.name}</div>
sider가 리뷰 달아준 사항도 확인하고 픽스해주세요!

2021-11-03 02:07 UTC, yeonuk-hwang commented on src/component/ProductContainer/ProductContainer.js
> +/* eslint-disable react/destructuring-assignment */
eslint가 조언해주는 사항들은 disabled 하기보다는 어떤 조언인지 확인하고 그부분을 fix 하는게 맞습니다! 그게 린트를 쓰는 목적이고요!

2021-11-03 02:07 UTC, yeonuk-hwang commented on src/component/ProductContainer/ProductContainer.js
> +import '../ProductContainer/ProductContainer.scss';
같은 것 import 를 두번하는 것 같습니다!!
***
PR 올리신 후에는 반드시 github에서 File Changed 탭 확인해서 내가 작성한 코드에 실수는 없는지, 내가 의도하지 않은 작업물들이 올라가지 않았는지 확인하는 습관을 들여주세요! PR을 요청할 때의 마음가짐은 실제 내가 등록한 코드가 바로 배포되어서 유저들이 바로 사용하게 된다고 생각하고 해주세요.(물런 지금은 학습과정이니까 작업이 완료되지 않아도 피드백을 목적으로 추가기능구현중 라벨을 붙이고 PR을 요청할수도 있지만 리뷰 요청하기 전에는 스스로 한번 꼭 점검해주세요!!)

2021-11-03 02:07 UTC, yeonuk-hwang commented on src/component/ProductContainer/ProductContainer.js
> +      <main className="productContainer">
네스팅을 통해서 이 컴포넌트의 스타일이 다른 컴포넌트에게 영향을 미치지 않도록 컴포넌트의 최상위 태그의 className은 컴포넌트 명과 동일하게 해주세요 일반적으로 className은 팀 컨벤션에 따라 camelCase또는 snake_case로 짓는게 일반적이지만 최상위 태그의 경우에는 컴포넌트 명과 동일하게 PascalCase로 지어주는 게 좋습니다(유니크하게 지어서 다른 className과 중복되지 않게 하기 위해서)

2021-11-03 02:07 UTC, younuk23 commented on src/component/ProductContainer/ProductContainer.js
> +          src="./images/unsplash_bed.jpg"
```suggestion
          src="/images/unsplash_bed.jpg"
```
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!
예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2021-11-03 02:07 UTC, younuk23 commented on src/component/ProductContainer/ProductContainer.scss
> +  .productInfo {
최상위 태그를 제외하고는 이렇게 부여하는 스타일 없이 네스팅만을 위해서 className을 부여하고 scss에 작성하는것은 불필요합니다!

2021-11-03 02:07 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +// import Nav from '../../component/Nav/Nav';
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2021-11-03 02:07 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +      });
예시코드를 복붙해서 그대로 쓰시기 보다는 불필요한 부분(주석 부분, 기본값 부분)등은 처리하시고 작성하시는게 좋지 않을까요?

2021-11-03 02:07 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +          {/* <p className="menu">menu</p> */}
위의 주석부분에 남겨드린 코멘트와 동일합니다

2021-11-03 02:07 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +          {product.map(product => {
product라는 배열안에 하나하나의 요소들이 product 인건 조금 어색해보입니다! 배열부분을 복수형으로 바꾸는 등의 처리를 통해서 명확히 구분해주는게 좋아보이네요

2021-11-03 02:07 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.scss
> +  flex-wrap: wrap;
flex관련된 속성들끼리 붙여두는게 나아보입니다  width가 중간에 들어가는것 보다는요!
css 작성 순서 컨벤셔도 항상 신경써주시고 전반적으로 점검 한번씩 해주세요!

2021-11-03 04:20 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.js
> +/* eslint-disable react/destructuring-assignment */
eslint를 사용하는 이유를 확실히 알았습니다! 앞으로는 eslint의 조언 사항에 따라 fix하겠습니다.

2021-11-03 04:22 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.js
> +import '../ProductContainer/ProductContainer.scss';
네!

2021-11-03 04:24 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.js
> +      <main className="productContainer">
최상위 태그는 pascalCase 적용..! 감사합니다~

2021-11-03 04:32 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +// import Nav from '../../component/Nav/Nav';
제가 다시 보고싶어 주석 처리를 해뒀었는데 커밋 이력에 남겨진 걸 볼 수 있다는 걸 깜빡했습니다.
불필요한 주석은 모두 삭제 처리하겠습니다!

2021-11-05 05:20 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요 지원님!
그리고 기존 리뷰 및 사이더에서 반영 안된것들 남아있는데 꼭 반영해주세요!!

2021-11-05 05:20 UTC, younuk23 commented on src/component/ProductContainer/ProductContainer.scss
> +  flex-direction: column;
기본적으로 block요소들은 세로쌓임이라서 자식요소들이 block이라면 flex, column 부여할 필요가 없는데 이렇게 부여하신 이유가 있나요??

2021-11-05 05:20 UTC, younuk23 commented on src/component/ProductContainer/ProductContainer.scss
> +  .productName {
셀렉터끼리 공백 가독성 신경써주세요!! PR 올린후에는 꼭 확인해주세요!

2021-11-05 05:20 UTC, younuk23 commented on src/component/ProductContainer/ProductContainer.scss
> +    font-weight: normal;
normal은 기본값입니다! 굳이 따로 부여할 필요 없어보이네요

2021-11-05 05:20 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +    fetch('http://localhost:3000/data/sandBag.json', {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2021-11-05 05:20 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +      method: 'GET',
get method는 기본값입니다

2021-11-05 05:20 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +              인기순 ▼{isModalOn === true ? 'optionBox' : null}
=== true 부분은 불필요한 것 같네요 그리고 true일 경우만 처리하려면 삼항연산자보다는 &&연산자가 간결합니다!
```suggestion
              인기순 ▼{isModalOn && 'optionBox'}
```

2021-11-05 05:20 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +                key={productInfo.id}
productInfo 구조분해할당해서 사용하면 편하겠네요!

2021-11-05 05:20 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.scss
> +}
Font 같은 경우에는 여기서 개별적으로 처리할게 아니라 common.scss 등에서 처리하는게 적합합니다!

2021-11-05 05:21 UTC, younuk23 commented
지원님! 이 브랜치에서 기능까지 진행하기보다는 여기서 레이아웃 리뷰사항 마무리해서 머지 받으시고 그다음에 다시 브랜치파서 기능 구현하시는게 목적별로 브랜치분리하는 것에 맞아보입니다!! 만약 여기서 기능까지 구현하시면은 이 PR 계속 머지 안되고 점점 수정사항 더 쌓이게 될 것 같네요!!

2021-11-05 05:42 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.scss
> +  .productName {
PR 후 체크하지 못한 부분이 굉장히 많았네요.. scssc의
공백 가독성 체크에 신경쓰겠습니다.

2021-11-05 05:46 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.scss
> +    font-weight: normal;
제가 작성해 놓고도 왜 작성했을지 모르겠네요..ㅜㅜ

2021-11-05 05:50 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +    fetch('http://localhost:3000/data/sandBag.json', {
생략하고 보니 fetch함수가 훨씬 간결해졌습니다. 감사합니다!

2021-11-05 06:02 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +              인기순 ▼{isModalOn === true ? 'optionBox' : null}
&& 연산자를 사용하는 것에 있어 완전히 이해하지 못해
사용하지 못했는데 앞으로는 true일 경우만 처리할 땐 && 연산자를
애용해보도록 하겠습니다!

2021-11-05 08:07 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +                key={productInfo.id}
함수의 인자를 구조 분해 할당이 가능한 지는 몰랐어요!
시간이 오래 걸리긴 했지만.. 새로운 것을 배워서 뿌듯합니다 감사합니다!

2021-11-05 08:09 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +    console.log(modalInfo);
수정 완료했습니다

2021-11-05 08:12 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.scss
> +  flex-direction: column;
이미지 태그가 인라인 속성을 가지고 있어 옆에 붙을 거라고 생각해 display: flex를 적용했습니다.
img 태그를 block 속성으로 만들고 사용하는 것이 나을까요?

2021-11-05 09:26 UTC, younuk23 commented on src/component/ProductContainer/ProductContainer.scss
> +  flex-direction: column;
의도하신 경우라면 괜찮습니다!! 👍

2021-11-05 09:26 UTC, younuk23 commented on src/pages/ProductLists/ProductLists.js
> +              인기순 ▼{isModalOn === true ? 'optionBox' : null}
&& || 연산자 단축평가 라는 키워드로 찾아보시면 어떤식으로 동작하는 건줄 알 수 있을 겁니다!!

2021-11-05 09:27 UTC, younuk23 commented
<Filtering 기능 구현 관련 질문>

①백엔드로부터 filter()와 sort()가 적용된 데이터를 받으면 제가 정렬하는 방법이 있다는 것과
②제가 직접 함수와 메서드를 사용해 원하는 조건에 맞는 컴포넌트를 나타나게 하는 방법이 있다는 것을 알게 되었습니다.
①번의 방법으로 작업을 하기 전에 ②번의 방법으로 진행하고자 했습니다.
filter 메서드를 작동시킬 수 있는 함수를 제작해 적용하고 싶은데 이틀을 투자해 작업했지만 도저히 기능 구현에 대한
실마리가 잡히질 않습니다. 이에 대해서 코드를 어떻게 풀어나가야 해결이 될 지와 같은 팁이나 과정을 너무나
알고싶습니다.

=> 지원님 이부분 아까 도현님이랑 질문 하시는 것 본 것 같은데 해결 된건가요?? 아니면 추가 가이드가 필요하신 상황인가요!

2021-11-05 12:08 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.js
> +          <div className="brandName">{this.props.name}</div>
픽스 완료했습니다!

2021-11-08 02:46 UTC, saengmotmi reviewed
리뷰 확인해주세요!

2021-11-08 02:46 UTC, saengmotmi commented on public/data/productData.json
> +    "discountPrice": 350000,
할인율, 할인 후 가격을 두개 다 받는건가요? 가격, 할인율을 받거나 가격, 할인가격을 받는게 더 맞지 않나 싶어요

2021-11-08 02:46 UTC, saengmotmi commented on src/component/Modal/Modal.scss
> +  height: 40px;
가급적 고정 가로, 세로의 사용을 피하고, 꼭 필요한 경우가 아니라면 부모 요소의 크기는 자식 요소 + margin, padding을 통해 자연히 결정될 수 있도록 해주세요.

2021-11-08 02:46 UTC, saengmotmi commented on src/component/ProductContainer/ProductContainer.js
> +/* eslint-disable react/destructuring-assignment */
@betterplaywon 린트 disabled 삭제해주세요

2021-11-08 02:46 UTC, saengmotmi commented on src/component/ProductContainer/ProductContainer.js
> +          <div className="brandName">{this.props.name}</div>
@betterplaywon 수정 안된 것 같습니다

2021-11-08 02:46 UTC, saengmotmi commented on src/pages/ProductLists/ProductLists.js
> +        </div> */}
구현이 끝났다면 정리해주세요

2021-11-08 02:46 UTC, saengmotmi commented on src/pages/ProductLists/ProductLists.js
> +                      key={modalMenu.id}
모달이 여러 개 띄워져야 하나요...?

2021-11-08 04:31 UTC, betterplaywon commented on public/data/productData.json
> +    "discountPrice": 350000,
백엔드 분들에게 할인율, 원가, 할인 후 가격 데이터를 받기로 의견 조율을 해서 가격 관련 데이터를
모두 작성했습니다.  멘토님이 말씀해주신 방법처럼 백엔드로부터 필요한 데이터만 받아와
제가 계산하는 방법은 미처 떠올리지를 못했는데, 다음부턴 계산이 가능해보이는 부분이 있다면
백엔드와 협의 후 제가 계산하는 코드를 작성할 수 있도록 진행하겠습니다.

2021-11-08 06:06 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.js
> +/* eslint-disable react/destructuring-assignment */
네!

2021-11-08 06:07 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +                      key={modalMenu.id}
테스트 코드였는데 미처 지우지 못했습니다. 수정했습니다!

2021-11-08 06:07 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +        </div> */}
정리 완료했습니다.

2021-11-08 06:08 UTC, betterplaywon commented on src/component/ProductContainer/ProductContainer.js
> +          <div className="brandName">{this.props.name}</div>
구조분해할당으로 재수정 완료했습니다.

2021-11-08 08:45 UTC, betterplaywon commented on src/component/Modal/Modal.scss
> +  height: 40px;
자식 요소로 부모 요소의 크기를 지정하는 방법을 꾸준히 사용해보면서 습관화 시켜보겠습니다.
말씀해주셔서 감사합니다!

2021-11-08 11:09 UTC, saengmotmi reviewed
리뷰 확인해주세요!

2021-11-08 11:09 UTC, saengmotmi commented on public/data/productData.json
> +    "star_rate": "1.5000000"
price, star_rate가 문자열로 표시되는게 맞나요?

2021-11-08 11:09 UTC, saengmotmi commented on public/data/productData.json
> +    "discount_rate": "21",
이것도 마찬가지입니다

2021-11-08 11:09 UTC, saengmotmi commented on src/pages/ProductLists/ProductLists.js
> +          })}
이 경우에는 구조분해할당 없이 쓰는게 더 잘보이지 않을까요? 혹은 다음과 같이 쓸거 같습니다
```suggestion
        <div className="singleProduct">
          {product.map(productInfo => <ProductContainer key={productInfo.id} {...productInfo} />)}
```

2021-11-08 11:09 UTC, saengmotmi commented on src/pages/ProductLists/ProductLists.js
> +  };
이 부분은 내일 라이브 리뷰 시간에 같이 보겠습니다

2021-11-08 11:36 UTC, betterplaywon commented on public/data/productData.json
> +    "star_rate": "1.5000000"
백엔드와 소통 후 정수 형태로 변환하기로 결정했습니다.

2021-11-08 11:37 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +  };
질문 드리고 싶었던 부분인데 체크해주셔서 감사합니다

2021-11-08 11:50 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +          })}
rest parameter에 대해 오늘 공부하고 나서 바로 적용해보도록 하겠습니다.
이건 완전 꿀팁이네요 와.... 저도 모르게 소리내면서 감탄했어요

2021-11-08 12:09 UTC, betterplaywon commented on src/pages/ProductLists/ProductLists.js
> +          })}
rest parameter를 사용해주면 비구조화 할당을 해주지 않아도 되는건가요?

2021-11-10 06:27 UTC, saengmotmi commented
@betterplaywon 고생하셨습니다 👍

2021-11-10 06:27 UTC, merged