Add : 레이아웃 css 및 항목 별 mock 데이터로 적용
wecode-bootcamp-korea/26-1st-Homes-frontend pull request #3
Opened 2021-11-03 01:17 UTC by ysh0514

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-11-03 02:08 UTC, younuk23 commented
- 성호님! PR 본문 작성, 라벨 처리, PR 제목 양식에 맞춰주시고 사이더 리뷰 반영해주세요! 그 뒤에 제가 리뷰하겠습니다!!

2021-11-04 05:12 UTC, younuk23 commented
성호님 수정이 완료되서 리뷰 요청하시는 것이면 수정요청 라벨은 제거해주세요! 라벨관리도 소통에 중요한 부분입니다!

2021-11-04 05:19 UTC, younuk23 requested changes
수고하셨습니다 성호님 리뷰확인 및 반영해주세요!!

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
>  export class Detail extends Component {
import 구문과 컴포넌트 사이에는 한 줄 공백이 부여되어있는게 가독성에 좋습니다(다른 문맥들 사이에는 공백을 주는 것이 좋습니다)

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +    fetch('http://localhost:3000/data/data.json', {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +      method: 'GET',
GET method 또한 기본값이므로 생략가능합니다.

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +      <div className="detailPageBox">
render 위, return 위쪽 한줄씩 공백 주세요 가독성 항상 신경써주시는게 좋습니다!

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +      <div className="detailPageBox">
네스팅을 통해서 이 컴포넌트의 스타일이 다른 컴포넌트에게 영향을 미치지 않도록 컴포넌트의 최상위 태그의 className은 컴포넌트 명과 동일하게 해주세요 일반적으로 className은 팀 컨벤션에 따라 camelCase또는 snake_case로 짓는게 일반적이지만 최상위 태그의 경우에는 컴포넌트 명과 동일하게 PascalCase로 지어주는 게 좋습니다(유니크하게 지어서 다른 className과 중복되지 않게 하기 위해서)

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.scss
> +  .ImageAndProduct {
최상위 태그를 제외한 className에서는 PascalCase 사용은 지양해주세요

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.scss
> +    width: 100%;
이미 block요소의 특징을 가지고 있기에 이 코드는 불필요합니다 왜 불필요한지 코멘트로 한번 달아주세요!

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.scss
> +    justify-content: center;
- CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 
- 일전에 안내해드린 [css 속성순서 컨벤션](https://www.notion.so/wecode/Westagram-JS-Refactoring-Checklist-dcff20de07b6449d89d82980e7af9cba#12ef362870c54d928ad6f56dab0b4b0e) 확인하시고 지켜서 작성해주세요

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.scss
> +        .costAndPercent {
style을 부여하지 않는 경우에는 굳이 className을 지정할 필요 없습니다!

2021-11-04 05:19 UTC, younuk23 commented on src/pages/Detail/Detail.scss
> +      height: 550px;
height의 경우에는 bottom-up 방식으로 레이아웃을 작성하는 게 좋습니다! 따라서 특정 경우를 제외하고는 부모의 height를 명시적으로 지정하는 것은 유지보수를 힘들게 만들 수 있습니다! 노션에서 셀프 리팩토링 체크리스트 한번 다시 읽어보시고 적용해주세요!

2021-11-04 06:13 UTC, ysh0514 commented on src/pages/Detail/Detail.scss
> +    width: 100%;
어차피 가로를 100퍼센트 사용하기때문에 사용 할 필요가 없습니다

2021-11-04 06:49 UTC, ysh0514 commented on src/pages/Detail/Detail.scss
> +      height: 550px;
우선 노션 체크리스트에는 확인을 못해서 나름대로 수정을 해봤습니다 이미지와 우측 박스의 height값을 없애서 해결했습니다

2021-11-05 05:26 UTC, younuk23 commented
처음으로 함수를 적용 해봤고 정말 어렵고 에러도 많았지만 하나를 성공하니 다음부턴 수월했습니다 너무 뿌듯합니다.
=> 👍 👍 

성장 포인트 너무 잘 기록해주셨고 PR 본문에서 하나 피드백 드리자면  
- 구현사항 설명 작성시 조금 더 어떻게(HOW)에 초점을 맞춰서 작성해주세요!! 지금은 무엇을 했는지에 대해서 설명하고 있네요!
구현사항을 잘 적으면서 내가 어떻게 구현했는지 스스로 이해도를 점검해볼 수 있으며 나중에 내가 어떤 고민을 하고 문제를 어떻게 해결했는지 점검해보면서 스스로를 회고해볼 수 있는 좋은 자산이 됩니다!

2021-11-05 05:26 UTC, younuk23 commented
리뷰 요청하시는 거면 리뷰요청 라벨 붙여주세요!!

2021-11-05 06:08 UTC, ysh0514 commented on src/pages/Detail/Detail.js
> +                <div className={buttonDropDown == true ? 'firstOnOff' : ''}>
수정완료! push 는 하지 않겠습니다

2021-11-05 06:10 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +                <div className={buttonDropDown == true ? 'firstOnOff' : ''}>
반영이 된 부분이 push 되지 않았습니다! 반영하시고 push 해주세요!

2021-11-05 06:16 UTC, ysh0514 commented
> 리뷰 요청하시는 거면 리뷰요청 라벨 붙여주세요!!

2021-11-05 06:17 UTC, ysh0514 commented
피드백 주신 pr 본문의 기능 구현을 옵션 선택창을 통해 기술해보았습니다 . 피드백이 더 필요하면 부탁드립니다~

2021-11-05 06:19 UTC, younuk23 requested changes
성호님 코멘트로 남기기보다 페어로 한번 보는게 좋을 것 같아서 한번 찾아와주세요!!

2021-11-05 06:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +    fetch('http:/data/data.json')
에러발생할 것 같네요!! 확인해보셨나요?
```suggestion
    fetch('/data/data.json')
```
이렇게 적어주셔야지 현재 실행되고 있는 포트로 인식이됩니다! 그리고 data.json이란 파일명보다는 어떤 데이터인지 알아볼 수 있는 파일명으로 지어주시는게 좋습니다!! 모든 이름들은 다 명확하게!

2021-11-05 06:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +      buttonValue: buttonValue === true ? false : true,
```suggestion
      buttonValue: !buttonValue
```
비교연산자의 값이 어차피 true or false이기에 === true등은 실행할 필요가 없습니다.
그리고 삼항연산자는 condition ? true일경우 값 : false일경우 값 형태로 이루어져 있는데 만약 불린값을 원하는 거면 굳이 삼항연산자 쓸 필요가 없습니다!!

2021-11-05 06:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +      buttonValue: buttonValue === true ? false : true,
다른 부분도 비슷한 내용 있어보이는데 전체적으로 점검 후 수정해주세요!

2021-11-05 06:19 UTC, younuk23 commented on src/pages/Detail/Detail.scss
> +      height: 550px;
2주차 Westagram 참고자료에 있습니다 확인해보시면 됩니다!!

2021-11-05 06:19 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +  };
성호님 이 로직에 대해서 얘기한번 나눠보시죠!! 저한테 오셔서 질문주세요!!

2021-11-10 05:09 UTC, saengmotmi commented
@ysh0514 어제 구두로 리뷰드린 내용 반영되셨으면 push 하시고 알려주세요!

2021-11-10 05:57 UTC, ysh0514 commented
> @ysh0514 어제 구두로 리뷰드린 내용 반영되셨으면 push 하시고 알려주세요!

2021-11-10 08:30 UTC, saengmotmi commented
고생하셨습니다~ 👍

2021-11-10 08:30 UTC, merged