Feature/login
wecode-bootcamp-korea/26-1st-Homes-frontend pull request #4
Opened 2021-11-03 02:57 UTC by JangSaeYoung

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 페이지 레이아웃 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 클론 홈페이지를 참고한 HTML, CSS 레이아웃 구현 
2. 팀 결정에 따른 포인트 칼라 지정하여 변경

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 위스타그램에 이어 로그인 페이지 레이아웃을 복습하듯이 다시 해볼 수 있었다. 
- placeholder 내부에 이미지 넣기 위한 absolute 사용. / placeholder의 다양한 속성을 구글링을 통해 살펴볼 수 있었다.

<br />

## :: 기타 질문 및 특이 사항
- 리팩토링 예정입니다.

2021-11-04 01:24 UTC, younuk23 commented
고생하셨습니다 세영님!! 
- 사이더가 리뷰 단 사항들이 반영이 안되어있습니다! 반영 해주세요!!
- PR 본문은 좀 더 상세하게 작성해주세요, 최근 작업주제 체크가 안되어있습니다 체크 해주세요!
- 구현사항 설명 작성시 조금 더 어떻게(HOW)에 초점을 맞춰서 작성해주세요!!
구현사항을 잘 적으면서 내가 어떻게 구현했는지 스스로 이해도를 점검해볼 수 있으며 나중에 내가 어떤 고민을 하고 문제를 어떻게 해결했는지 점검해보면서 스스로를 회고해볼 수 있는 좋은 자산이 됩니다!

2021-11-04 05:10 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요~!

2021-11-04 05:10 UTC, yeonuk-hwang commented on src/pages/Login/Login.js
> +  };
이 두개의 함수 input의 name property와 javascript의 계산된속성명 문법 이용해서 하나로 합칠 수 있어보입니다! 시도해보세요!

2021-11-04 05:10 UTC, yeonuk-hwang commented on src/pages/Login/Login.js
> +      <div id="loginPage">
- `id` 보다는 `className` 을 활용해주시기 바랍니다.
- HTML에서  `id` 는 문서 내에서 유일해야 합니다. 이러한 이유로 단일 요소를 다루는 경우 `id`를 사용할 수 있습니다.
- 하지만 정말로 해당 요소에 대한 이벤트나 스타일 핸들링이 프로젝트 전체에서 단 한번만 사용 되는지 충분히 고민해야합니다. 일반적으로 컴포넌트는 재사용 될 수 있기 때문에 같은 요소가 여러번 생성될 수 있습니다. 이러한 이유로 보통의 경우에는 `className` 을 사용합니다.

2021-11-04 05:10 UTC, yeonuk-hwang commented on src/pages/Login/Login.js
> +      <div id="loginPage">
네스팅을 통해서 이 컴포넌트의 스타일이 다른 컴포넌트에게 영향을 미치지 않도록 컴포넌트의 최상위 태그의 className은 컴포넌트 명과 동일하게 해주세요 일반적으로 className은 팀 컨벤션에 따라 camelCase또는 snake_case로 짓는게 일반적이지만 최상위 태그의 경우에는 컴포넌트 명과 동일하게 PascalCase로 지어주는 게 좋습니다(유니크하게 지어서 다른 className과 중복되지 않게 하기 위해서)

2021-11-04 05:10 UTC, yeonuk-hwang commented on src/pages/Login/Login.js
> +      <div id="loginPage">
```suggestion
      <div className="Login">
```

2021-11-04 05:10 UTC, younuk23 commented on src/pages/Login/Login.js
> +            <img id="homeLogo" src="./images/home.png" alt="집꾸미기로고" />
src의 주소를 public 폴더 하위에 접근할 때는 절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2021-11-04 05:10 UTC, younuk23 commented on src/pages/Login/Login.js
> +            <button className="viewBtn3">네이버 계정으로 로그인</button>
viewBtn 1,2,3등의 이름은 의미가 명확히 드러나지 않기 때문에 의미가 드러나는 이름으로 지어주시는게 좋습니다!
그리고 만약 1,2,3에 대해서 모두 같은 스타일이 적용된다면 하나의 viewBtn이라는 className으로 통일해도 좋을 것 같네요!

2021-11-04 05:10 UTC, younuk23 commented on src/pages/Login/Login.js
> +                  : true
```suggestion
                !(this.state.pwd.length > 7)
```
이미 비교연산자의 평가값이 true or false 이므로 굳이 삼항연산자 없이 not 연산자 사용해서 표현가능합니다!

2021-11-04 05:10 UTC, younuk23 commented on src/pages/Login/Login.scss
> +    .Logo {
최상위 태그를 제외한 나머지 className은 camelCase 또는 snake_case를 사용해서 작성해주세요(둘 중 팀에서 합의한 컨벤션에 따르면 됩니다) 그리고 최상위 태그를 제외하고는 스타일을 부여하지 않는 경우는 굳이 className을 지정할 필요가 없습니다(지금도 Logo에 대한 스타일은 부여되지 않는 것으로 보이네요!)

2021-11-04 05:10 UTC, younuk23 commented on src/pages/Login/Login.scss
> +    justify-content: center;
justify-content 속성은 display:flex가 지정되어야 적용이 되는 속성입니다 여기서는 불필요해보이네요!

2021-11-04 05:10 UTC, younuk23 commented on src/pages/Main/Main.js
> -import React, { Component } from 'react';
Main 부분을 삭제하신 이유가 있나요??

2021-11-04 05:10 UTC, younuk23 commented on src/pages/Login/Login.scss
> +    display: block;
container는 div 태그로 이미 block의 속성을 가지고 있습니다. 다만 부모인 loginPage에서 flex를 부여했기에 자식요소인 container는 inline-block의 display를 가지게 되는데요! 수직쌓임을 하려면 굳이 display:flex를 부모에 부여할 필요 없을 것 같고, 만약 가운데 정렬이 필요해서 부모에서 flex, center, center 속성을 부여한 것이라면 flex-direction을 column으로 지정하는 식으로 하는 것이 좀 더 효율적일 것 같네요! 이해 안되시면 와서 질문주세요!!

2021-11-04 06:12 UTC, JangSaeYoung commented on src/pages/Login/Login.scss
> +    display: block;
리뷰 감사합니다. 하나씩 수정하며 점검해보겠습니다!

2021-11-05 05:24 UTC, younuk23 requested changes
세영님 리뷰사항 반영 잘 하셨네요! 그리고 성장포인트 기록도 잘 해주셨네요!! 👍 
제가 단 코멘트 하나랑 사이더 리뷰사항 반영해주세요!
주로 구조분해할당 관련되서 사이더 리뷰 달렸는데 이해 안되거나 모르시겠으면 질문주세요!!
그부분 해결되면 머지하겠습니다!

그리고 커밋 메세지 작성하실때는 가이드라인에 맞춰서 작성해주시는게 추후 커밋에서 무슨 일이 있었는지 파악하기 쉽습니다!!
- 아래 문서 참고해보세요
- [커밋 메세지 가이드라인](https://www.notion.so/Commit-Message-Guidelines-eb3d8ebc0d014c26848ee628934ae430)

2021-11-05 05:24 UTC, younuk23 commented on src/pages/Login/Login.js
> +    fetch('http://localhost:3000/data/commentData.json', {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2021-11-05 05:25 UTC, younuk23 commented
그리고 수정완료해서 리뷰요청 라벨 다실때는 기존의 수정요청 라벨은 제거해주시면 됩니다!

2021-11-08 11:13 UTC, saengmotmi reviewed
마이너한 부분이라 일단 머지하겠습니다. 다음 PR에서 리뷰 반영해주세요!

2021-11-08 11:13 UTC, saengmotmi commented on public/data/commentData.json
> +]
이 파일은 혹시 용도가 어떻게 되나요?

2021-11-08 11:13 UTC, saengmotmi commented on src/pages/Login/Login.js
> +            <img id="emailIcon" src="./images/email.png" alt="이메일아이콘" />
스타일링 목적이라면 id -> className으로 사용해주세요

2021-11-08 11:13 UTC, saengmotmi commented on src/pages/Login/Login.scss
> +      }
중복되는 속성들이 보이는데 어떻게 중복을 제거할 수 있을까요?

2021-11-08 11:13 UTC, saengmotmi commented on src/pages/Login/Login.js
> +    fetch('http://10.58.4.252:8000/users/signin', login_info)
위와 같은 방법이라면 api 주소가 달라질 경우, 일일이 각 컴포넌트에서 수정해야하기에 유지보수가 어려워보입니다. 
유지보수를 위해 src 폴더 하위에 config.js 파일을 생성하여 해당파일에서 변수에 api주소 값을 할당해 import해서 사용해주세요.

2021-11-08 11:13 UTC, merged